baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Steve Chovanec'
copyright = 'Copyright &copy; Steve Chovanec'
sectionPagesMenu = 'main'

[Params]
imageThumbSize = 600
imageFullSize = 3000
