name: "Steve Chovanec’s Blog"
author: "Steve Chovanec"
#description: "Learning to use Jekyll"

github_url: "https://github.com/schovanec/schovanec.github.io"

url: "http://localhost:4000"
feed: "/atom.xml"

paginate: 10
paginate_path: "/page/:num"

permalink: "/archive/:year/:month/:day/:title"

markdown:     redcarpet
highlighter:  pygments

redcarpet:
  extensions:
    - smart
    - tables
    - no_intra_emphasis
    - footnotes
    - disable_indented_code_blocks

exclude: ["Gemfile", "Gemfile.lock"]