name: "Steve Chovanec’s Blog"
description: "Learning to use Jekyll"

url: "http://localhost:4000"
feed: "/feed.xml"

paginate: 10

permalink: pretty
highlighter: pygments

exclude: ["Gemfile", "Gemfile.lock"]