title: "Steve Chovanec’s Blog"
author: "Steve Chovanec"
#description: "Learning to use Jekyll"

url: "http://www.stevechovanec.com"

#feed_url: "/atom.xml"
#about_url: /about/
#archive_url: /archive/
github_url: "https://github.com/schovanec/schovanec.github.io"

disqus_shortname: schovanec-blog-test

paginate: 10
paginate_path: "/page/:num/"

permalink: "/archive/:year/:month/:day/:title/"

highlighter: rouge

plugins:
  - jekyll-sitemap

# front-matter defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

repository: schovanec/schovanec.github.io
