title: "Steve Chovanec’s Blog"
author: "Steve Chovanec"
#description: "Learning to use Jekyll"

url: "http://www.stevechovanec.com"

#feed_url: "/atom.xml"
#about_url: /about/
#archive_url: /archive/
github_url: "https://github.com/schovanec/schovanec.github.io"

google_analytics_id: UA-58832130-1

paginate: 10
paginate_path: "/page/:num/"

permalink: "/archive/:year/:month/:day/:title/"

highlighter: rouge

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

repository: schovanec/schovanec.github.io
